-- Makademi schema + seed data (auto-generated, do not hand-edit).
-- Dialect: mysql
SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

DROP TABLE IF EXISTS gallery_images;
DROP TABLE IF EXISTS gallery_categories;
DROP TABLE IF EXISTS programs;
DROP TABLE IF EXISTS categories;
DROP TABLE IF EXISTS admin_users;

CREATE TABLE admin_users (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  username VARCHAR(64) NOT NULL UNIQUE,
  password_hash VARCHAR(255) NOT NULL,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  last_login_at DATETIME NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE categories (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) NOT NULL UNIQUE,
  slug VARCHAR(128) NOT NULL UNIQUE,
  badge_class VARCHAR(64) NOT NULL DEFAULT 'engineering',
  sort_order INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE programs (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  title VARCHAR(255) NOT NULL,
  description TEXT NOT NULL,
  category_id INT NOT NULL,
  duration VARCHAR(64) NOT NULL DEFAULT '',
  location VARCHAR(128) NOT NULL DEFAULT '',
  detail_url VARCHAR(255) NOT NULL DEFAULT '',
  is_published TINYINT NOT NULL DEFAULT 1,
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
  updated_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE gallery_categories (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  name VARCHAR(128) NOT NULL UNIQUE,
  slug VARCHAR(128) NOT NULL UNIQUE,
  badge_class VARCHAR(64) NOT NULL DEFAULT 'engineering',
  badge_text VARCHAR(128) NOT NULL DEFAULT '',
  description TEXT NOT NULL,
  sort_order INT NOT NULL DEFAULT 0
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE gallery_images (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  gallery_category_id INT NOT NULL,
  filename VARCHAR(255) NOT NULL,
  caption VARCHAR(500) NOT NULL DEFAULT '',
  sort_order INT NOT NULL DEFAULT 0,
  created_at DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- Categories
INSERT INTO categories (name, slug, badge_class, sort_order) VALUES ('Engineering & Technical', 'engineering-technical', 'engineering', 0);
INSERT INTO categories (name, slug, badge_class, sort_order) VALUES ('Maintenance & Production', 'maintenance-production', 'maintenance', 1);
INSERT INTO categories (name, slug, badge_class, sort_order) VALUES ('Banking & Finance', 'banking-finance', 'finance', 2);
INSERT INTO categories (name, slug, badge_class, sort_order) VALUES ('Telecom & Digital', 'telecom-digital', 'telecom', 3);
INSERT INTO categories (name, slug, badge_class, sort_order) VALUES ('Fire Safety & Emergency', 'fire-safety-emergency', 'fire', 4);
INSERT INTO categories (name, slug, badge_class, sort_order) VALUES ('Health, Safety & Environment', 'health-safety-environment', 'hse', 5);
INSERT INTO categories (name, slug, badge_class, sort_order) VALUES ('Corrosion & Integrity', 'corrosion-integrity', 'corrosion', 6);
INSERT INTO categories (name, slug, badge_class, sort_order) VALUES ('Management & Leadership', 'management-leadership', 'management', 7);
INSERT INTO categories (name, slug, badge_class, sort_order) VALUES ('Finance & Accounting', 'finance-accounting', 'finance', 8);
INSERT INTO categories (name, slug, badge_class, sort_order) VALUES ('High-Value Programs', 'high-value-programs', 'high-value', 9);

-- Programs
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Reservoir Modelling with Petrel', 'Advanced 3D reservoir modeling using Petrel software.', (SELECT id FROM categories WHERE name = 'Engineering & Technical'), '2 Weeks', 'Istanbul', '', 1, 0);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Well Testing, Completion & Production Operations', 'Comprehensive training on well completion design, testing operations, and production optimization techniques for modern oilfields.', (SELECT id FROM categories WHERE name = 'Engineering & Technical'), '2 Weeks', 'Istanbul', '', 1, 1);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Drilling Operations & Well Control Fundamentals', 'Essential well control principles and modern drilling operations.', (SELECT id FROM categories WHERE name = 'Engineering & Technical'), '2 Weeks', 'Istanbul', '', 1, 2);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Rotating Equipment Maintenance & Troubleshooting', 'Maintenance strategies for pumps, compressors, and turbines.', (SELECT id FROM categories WHERE name = 'Engineering & Technical'), '2 Weeks', 'Istanbul', '', 1, 3);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Static Equipment & Pressure Vessels Maintenance', 'Inspection and maintenance of pressure vessels and heat exchangers.', (SELECT id FROM categories WHERE name = 'Engineering & Technical'), '2 Weeks', 'Istanbul', '', 1, 4);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Piping Systems, Valves & Flanges Maintenance', 'Best practices for industrial piping and valve maintenance.', (SELECT id FROM categories WHERE name = 'Engineering & Technical'), '2 Weeks', 'Istanbul', '', 1, 5);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Electrical Safety & LV/MV Systems', 'Safety protocols for low and medium voltage electrical systems.', (SELECT id FROM categories WHERE name = 'Engineering & Technical'), '2 Weeks', 'Istanbul', '', 1, 6);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Power Systems & Protection', 'Design and configuration of electrical power protection systems.', (SELECT id FROM categories WHERE name = 'Engineering & Technical'), '2 Weeks', 'Istanbul', '', 1, 7);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('PLC, Automation & I&C Systems', 'Industrial control systems programming and troubleshooting.', (SELECT id FROM categories WHERE name = 'Engineering & Technical'), '2 Weeks', 'Istanbul', '', 1, 8);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Ultrasonic Testing (UT) Level I & II', 'Certification in ultrasonic non-destructive testing methodologies.', (SELECT id FROM categories WHERE name = 'Engineering & Technical'), '2 Weeks', 'Istanbul', '', 1, 9);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Magnetic Particle Testing (MT) Level I & II', 'Certification in magnetic particle non-destructive testing.', (SELECT id FROM categories WHERE name = 'Engineering & Technical'), '2 Weeks', 'Istanbul', '', 1, 10);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Radiographic Testing (RT) Level I & II', 'Certification in industrial radiographic testing procedures.', (SELECT id FROM categories WHERE name = 'Engineering & Technical'), '2 Weeks', 'Istanbul', '', 1, 11);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Oil & Gas Procurement & Contract Management', 'Strategic procurement and contracting in the energy sector.', (SELECT id FROM categories WHERE name = 'Engineering & Technical'), '2 Weeks', 'Istanbul', '', 1, 12);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Logistics & Materials Management in Oil & Gas', 'Supply chain optimization for oilfield materials and logistics.', (SELECT id FROM categories WHERE name = 'Engineering & Technical'), '2 Weeks', 'Istanbul', '', 1, 13);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Downstream Operations Management', 'Refinery and petrochemical plant operations and management.', (SELECT id FROM categories WHERE name = 'Engineering & Technical'), '2 Weeks', 'Istanbul', '', 1, 14);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Process Safety & Operations Fundamentals', 'Core principles of process safety in hazardous environments.', (SELECT id FROM categories WHERE name = 'Engineering & Technical'), '2 Weeks', 'Istanbul', '', 1, 15);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Purchasing and Material Management', 'Advanced procurement strategies and inventory control.', (SELECT id FROM categories WHERE name = 'Management & Leadership'), '2 Weeks', 'Istanbul', '', 1, 16);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Internal Inspection of Pipelines', 'Pipeline integrity management and inline inspection technologies.', (SELECT id FROM categories WHERE name = 'Corrosion & Integrity'), '2 Weeks', 'Istanbul', '', 1, 17);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Risk Management Professional (RMP)', 'Comprehensive risk identification and mitigation strategies.', (SELECT id FROM categories WHERE name = 'Management & Leadership'), '2 Weeks', 'Istanbul', '', 1, 18);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Supply Chain Management', 'End-to-end supply chain optimization for industrial enterprises.', (SELECT id FROM categories WHERE name = 'Management & Leadership'), '2 Weeks', 'Istanbul', '', 1, 19);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Environment Management System', 'Implementation of ISO environmental management standards.', (SELECT id FROM categories WHERE name = 'Management & Leadership'), '2 Weeks', 'Istanbul', '', 1, 20);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Occupational Safety in Warehouses', 'Safety protocols and risk reduction in industrial warehousing.', (SELECT id FROM categories WHERE name = 'Management & Leadership'), '1 Week', 'Istanbul', '', 1, 21);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Advanced Business Administration', 'Executive administration skills for technical organizations.', (SELECT id FROM categories WHERE name = 'Management & Leadership'), '2 Weeks', 'Istanbul', '', 1, 22);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Strategic Leadership and Management', 'Transformational leadership methodologies designed specifically for senior managers and directors in high-stakes industrial environments.', (SELECT id FROM categories WHERE name = 'High-Value Programs'), '2 Weeks', 'Istanbul', '', 1, 23);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Advanced Oil and Gas Protection in Engineering', 'Security and asset protection for critical energy infrastructure.', (SELECT id FROM categories WHERE name = 'Management & Leadership'), '2 Weeks', 'Istanbul', '', 1, 24);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Human Resource Management', 'Modern HR practices for industrial workforce management.', (SELECT id FROM categories WHERE name = 'Management & Leadership'), '2 Weeks', 'Istanbul', '', 1, 25);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Advanced Systems Human Resources Planning and Personnel Management', 'Strategic workforce planning and personnel optimization.', (SELECT id FROM categories WHERE name = 'Management & Leadership'), '2 Weeks', 'Istanbul', '', 1, 26);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Develop Supervisory Skills and Service Excellence', 'Frontline leadership and service quality enhancement.', (SELECT id FROM categories WHERE name = 'Management & Leadership'), '2 Weeks', 'Istanbul', '', 1, 27);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Industrial Service Management', 'Optimization of industrial maintenance and support services.', (SELECT id FROM categories WHERE name = 'Management & Leadership'), '2 Weeks', 'Istanbul', '', 1, 28);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Skills Management', 'Competency mapping and technical skills development programs.', (SELECT id FROM categories WHERE name = 'Management & Leadership'), '2 Weeks', 'Istanbul', '', 1, 29);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Strategic Planning and Risk Management', 'Integration of enterprise risk with long-term strategic planning.', (SELECT id FROM categories WHERE name = 'High-Value Programs'), '2 Weeks', 'Istanbul', '', 1, 30);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Communication Course', 'Effective business communication for technical professionals.', (SELECT id FROM categories WHERE name = 'Management & Leadership'), '2 Weeks', 'Istanbul', '', 1, 31);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Billing Information Modeling', 'Advanced financial modeling for industrial billing systems.', (SELECT id FROM categories WHERE name = 'Management & Leadership'), '2 Weeks', 'Istanbul', '', 1, 32);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Occupational Health & Safety Management System (ISO 45001)', 'Complete framework for developing, implementing, and auditing ISO 45001 compliant occupational health and safety systems.', (SELECT id FROM categories WHERE name = 'Health, Safety & Environment'), '2 Weeks', 'Istanbul', '', 1, 33);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Fundamentals of Occupational Safety in Industrial Sites', 'Core safety practices for hazardous industrial environments.', (SELECT id FROM categories WHERE name = 'Health, Safety & Environment'), '1 Week', 'Istanbul', '', 1, 34);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Risk Management in Industrial Environments', 'Quantitative and qualitative risk assessment methodologies.', (SELECT id FROM categories WHERE name = 'Health, Safety & Environment'), '1 Week', 'Istanbul', '', 1, 35);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Incident Investigation & Root Cause Analysis', 'Systematic approaches to investigating industrial accidents.', (SELECT id FROM categories WHERE name = 'Health, Safety & Environment'), '1 Week', 'Istanbul', '', 1, 36);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Occupational Safety Management in the Oil & Gas Sector', 'Specialized safety management for hydrocarbon operations.', (SELECT id FROM categories WHERE name = 'Health, Safety & Environment'), '2 Weeks', 'Istanbul', '', 1, 37);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Institutional Safety Culture', 'Developing and sustaining a proactive organizational safety culture.', (SELECT id FROM categories WHERE name = 'Health, Safety & Environment'), '1 Week', 'Istanbul', '', 1, 38);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Artificial Intelligence in Industrial Safety Management', 'Applying AI and machine learning to predictive safety analytics.', (SELECT id FROM categories WHERE name = 'Health, Safety & Environment'), '1 Week', 'Istanbul', '', 1, 39);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Environmental Management System (ISO 14001)', 'Implementation of ISO 14001 environmental standards.', (SELECT id FROM categories WHERE name = 'Health, Safety & Environment'), '1 Week', 'Istanbul', '', 1, 40);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Firefighting in Oil Facilities (JOIFF Accredited)', 'Elite tactical firefighting training specifically designed for high-risk petrochemical and oil refinery environments, featuring live-fire simulations and JOIFF certification.', (SELECT id FROM categories WHERE name = 'Fire Safety & Emergency'), '10 Days', 'PETKİM Training Center, İzmir', 'courses/firefighting-joiff.html', 1, 41);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Initial Response to Industrial Fires', 'First responder tactics for incipient stage industrial fires.', (SELECT id FROM categories WHERE name = 'Fire Safety & Emergency'), '1 Week', 'Istanbul', '', 1, 42);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Fire Prevention in Industrial Facilities', 'Strategies for identifying and mitigating fire hazards.', (SELECT id FROM categories WHERE name = 'Fire Safety & Emergency'), '1 Week', 'Istanbul', '', 1, 43);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Industrial Corrosion and Prevention Methods', 'Advanced mitigation techniques for industrial corrosion.', (SELECT id FROM categories WHERE name = 'Corrosion & Integrity'), '2 Weeks', 'Istanbul', '', 1, 44);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Corrosion Protection in Industrial Facilities', 'Cathodic protection and anti-corrosion strategies.', (SELECT id FROM categories WHERE name = 'Corrosion & Integrity'), '1 Week', 'Istanbul', '', 1, 45);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Industrial Coating Systems & Corrosion Protection', 'Application and inspection of protective industrial coatings.', (SELECT id FROM categories WHERE name = 'Corrosion & Integrity'), '1 Week', 'Istanbul', '', 1, 46);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Industrial Emergency Management', 'Comprehensive framework for managing large-scale industrial emergencies.', (SELECT id FROM categories WHERE name = 'Fire Safety & Emergency'), '2 Weeks', 'Istanbul', '', 1, 47);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Emergency Planning & Incident Response', 'Developing robust emergency response plans and protocols.', (SELECT id FROM categories WHERE name = 'Fire Safety & Emergency'), '1 Week', 'Istanbul', '', 1, 48);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Crisis Management in Industrial Facilities', 'Strategic decision making during critical industrial events.', (SELECT id FROM categories WHERE name = 'Fire Safety & Emergency'), '1 Week', 'Istanbul', '', 1, 49);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Investigation of Major Industrial Incidents', 'Advanced techniques for investigating complex industrial disasters.', (SELECT id FROM categories WHERE name = 'Fire Safety & Emergency'), '1 Week', 'Istanbul', '', 1, 50);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Emergency Operations & Rescue Coordination', 'Tactical coordination of emergency rescue operations.', (SELECT id FROM categories WHERE name = 'Fire Safety & Emergency'), '2 Weeks', 'Istanbul', '', 1, 51);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Asset Management & Maintenance (ISO 55000)', 'Implementation of ISO 55000 asset management systems.', (SELECT id FROM categories WHERE name = 'Maintenance & Production'), '2 Weeks', 'Istanbul', '', 1, 52);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Fundamentals of Industrial Maintenance', 'Core principles of industrial equipment maintenance.', (SELECT id FROM categories WHERE name = 'Maintenance & Production'), '1 Week', 'Istanbul', '', 1, 53);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Predictive Maintenance Using Artificial Intelligence', 'Cutting-edge integration of machine learning algorithms with condition monitoring to predict and prevent industrial equipment failures.', (SELECT id FROM categories WHERE name = 'Maintenance & Production'), '1 Week', 'Istanbul', '', 1, 54);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Industrial Production Efficiency Improvement', 'Strategies for maximizing plant uptime and production efficiency.', (SELECT id FROM categories WHERE name = 'Maintenance & Production'), '2 Weeks', 'Istanbul', '', 1, 55);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Preventive Maintenance for Industrial Equipment', 'Designing and executing effective preventive maintenance programs.', (SELECT id FROM categories WHERE name = 'Maintenance & Production'), '1 Week', 'Istanbul', '', 1, 56);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('CMMS Maintenance Management Systems', 'Optimization of Computerized Maintenance Management Systems.', (SELECT id FROM categories WHERE name = 'Maintenance & Production'), '1 Week', 'Istanbul', '', 1, 57);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Root Cause Failure Analysis (RCA)', 'Methodologies for identifying the true causes of equipment failure.', (SELECT id FROM categories WHERE name = 'Maintenance & Production'), '1 Week', 'Istanbul', '', 1, 58);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Operational Reliability Management', 'Frameworks for improving overall equipment effectiveness (OEE).', (SELECT id FROM categories WHERE name = 'Maintenance & Production'), '2 Weeks', 'Istanbul', '', 1, 59);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Maintenance & Production Coordination', 'Bridging the gap between maintenance scheduling and production demands.', (SELECT id FROM categories WHERE name = 'Maintenance & Production'), '1 Week', 'Istanbul', '', 1, 60);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Maintenance Operational Performance Optimization', 'KPI tracking and performance improvement in maintenance teams.', (SELECT id FROM categories WHERE name = 'Maintenance & Production'), '1 Week', 'Istanbul', '', 1, 61);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Condition Monitoring & Vibration Analysis', 'Techniques for monitoring equipment health via vibration signatures.', (SELECT id FROM categories WHERE name = 'Maintenance & Production'), '1 Week', 'Istanbul', '', 1, 62);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Digital Transformation in the Oil & Gas Sector', 'Strategic implementation of digital technologies in energy operations.', (SELECT id FROM categories WHERE name = 'Telecom & Digital'), '2 Weeks', 'Istanbul', '', 1, 63);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Fundamentals of Institutional Digital Transformation', 'Core concepts of driving organizational digital change.', (SELECT id FROM categories WHERE name = 'Telecom & Digital'), '1 Week', 'Istanbul', '', 1, 64);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Data Analysis for Decision Support', 'Leveraging big data for strategic industrial decision making.', (SELECT id FROM categories WHERE name = 'Telecom & Digital'), '1 Week', 'Istanbul', '', 1, 65);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Artificial Intelligence in Process Automation', 'Applying AI to streamline and automate industrial processes.', (SELECT id FROM categories WHERE name = 'Telecom & Digital'), '1 Week', 'Istanbul', '', 1, 66);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Industrial Process Automation', 'Modern techniques for automating manufacturing and production.', (SELECT id FROM categories WHERE name = 'Telecom & Digital'), '1 Week', 'Istanbul', '', 1, 67);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('IT Service Management (ITIL)', 'ITIL framework implementation for industrial IT services.', (SELECT id FROM categories WHERE name = 'Telecom & Digital'), '2 Weeks', 'Istanbul', '', 1, 68);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Digital Transformation Project Management', 'Managing complex technology integration projects.', (SELECT id FROM categories WHERE name = 'Telecom & Digital'), '1 Week', 'Istanbul', '', 1, 69);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Digital Twin in Industrial Facilities', 'Creating and utilizing advanced digital twin models to simulate, analyze, and optimize physical industrial assets and processes.', (SELECT id FROM categories WHERE name = 'Telecom & Digital'), '1 Week', 'Istanbul', '', 1, 70);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Institutional Digital Innovation', 'Fostering a culture of technological innovation.', (SELECT id FROM categories WHERE name = 'Telecom & Digital'), '1 Week', 'Istanbul', '', 1, 71);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Change Management in Digital Transformation', 'Managing the human element of digital disruption.', (SELECT id FROM categories WHERE name = 'Telecom & Digital'), '1 Week', 'Istanbul', '', 1, 72);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Effective Leadership in Industrial Organizations', 'Leadership strategies tailored for technical environments.', (SELECT id FROM categories WHERE name = 'Management & Leadership'), '2 Weeks', 'Istanbul', '', 1, 73);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Supervisory Skills & Team Leadership', 'Essential skills for frontline industrial supervisors.', (SELECT id FROM categories WHERE name = 'Management & Leadership'), '1 Week', 'Istanbul', '', 1, 74);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Decision-Making & Problem Solving', 'Analytical approaches to complex industrial challenges.', (SELECT id FROM categories WHERE name = 'Management & Leadership'), '1 Week', 'Istanbul', '', 1, 75);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Institutional Strategic Planning', 'Long-term organizational strategy development.', (SELECT id FROM categories WHERE name = 'High-Value Programs'), '2 Weeks', 'Istanbul', '', 1, 76);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Institutional Change Management', 'Guiding organizations through structural and operational transitions.', (SELECT id FROM categories WHERE name = 'Management & Leadership'), '1 Week', 'Istanbul', '', 1, 77);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Leadership Communication Skills', 'Advanced communication techniques for technical leaders.', (SELECT id FROM categories WHERE name = 'Management & Leadership'), '1 Week', 'Istanbul', '', 1, 78);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Performance Management & Employee Motivation', 'Driving excellence in industrial workforces.', (SELECT id FROM categories WHERE name = 'Management & Leadership'), '1 Week', 'Istanbul', '', 1, 79);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Crisis Management & Leadership in Emergencies', 'Executive leadership during high-stress industrial crises.', (SELECT id FROM categories WHERE name = 'Management & Leadership'), '2 Weeks', 'Istanbul', '', 1, 80);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Emotional Intelligence for Leaders', 'Developing EQ for improved team management.', (SELECT id FROM categories WHERE name = 'Management & Leadership'), '1 Week', 'Istanbul', '', 1, 81);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Time Management & Productivity Enhancement', 'Optimizing personal and team efficiency.', (SELECT id FROM categories WHERE name = 'Management & Leadership'), '1 Week', 'Istanbul', '', 1, 82);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Financial Reporting According to International Standards (IFRS)', 'Comprehensive IFRS compliance for industrial enterprises.', (SELECT id FROM categories WHERE name = 'Finance & Accounting'), '2 Weeks', 'Istanbul', '', 1, 83);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Fundamentals of Financial Accounting', 'Core accounting principles for non-financial managers.', (SELECT id FROM categories WHERE name = 'Finance & Accounting'), '1 Week', 'Istanbul', '', 1, 84);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Financial Analysis & Decision-Making', 'Interpreting financial data to drive operational strategy.', (SELECT id FROM categories WHERE name = 'Finance & Accounting'), '1 Week', 'Istanbul', '', 1, 85);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Budget Preparation & Financial Control', 'Effective budgeting techniques for industrial departments.', (SELECT id FROM categories WHERE name = 'Finance & Accounting'), '1 Week', 'Istanbul', '', 1, 86);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Cost Management in Projects', 'Controlling expenditures in complex engineering projects.', (SELECT id FROM categories WHERE name = 'Finance & Accounting'), '1 Week', 'Istanbul', '', 1, 87);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Managerial Accounting', 'Internal financial reporting for management decision support.', (SELECT id FROM categories WHERE name = 'Finance & Accounting'), '2 Weeks', 'Istanbul', '', 1, 88);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Internal Audit & Financial Control', 'Establishing robust financial oversight mechanisms.', (SELECT id FROM categories WHERE name = 'Finance & Accounting'), '1 Week', 'Istanbul', '', 1, 89);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Investment Project Financial Evaluation', 'Assessing the viability of capital-intensive industrial investments.', (SELECT id FROM categories WHERE name = 'Finance & Accounting'), '1 Week', 'Istanbul', '', 1, 90);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Cash Flow Management', 'Optimizing liquidity in project-based organizations.', (SELECT id FROM categories WHERE name = 'Finance & Accounting'), '1 Week', 'Istanbul', '', 1, 91);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Financial Statement Analysis for Management', 'Extracting actionable insights from corporate financial statements.', (SELECT id FROM categories WHERE name = 'Finance & Accounting'), '1 Week', 'Istanbul', '', 1, 92);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Electric and Hybrid Vehicle Technology: 800V Architecture & BMS Diagnostics', 'Master modern 800V architectures, high-voltage safety, and advanced Battery Management System (BMS) diagnostics for the next generation of electric vehicles.', (SELECT id FROM categories WHERE name = 'Engineering & Technical'), '2 Weeks', 'Istanbul / Global', 'courses/electric-hybrid-vehicle.html', 1, 93);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Artificial Intelligence in Executive Decision-Making', 'Empowering C-suite executives with AI-driven strategic insights.', (SELECT id FROM categories WHERE name = 'High-Value Programs'), '2 Weeks', 'Istanbul', '', 1, 94);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Digital Twin in Oil Facilities', 'Advanced modeling of petrochemical infrastructure.', (SELECT id FROM categories WHERE name = 'Telecom & Digital'), '2 Weeks', 'Istanbul', '', 1, 95);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Institutional Innovation in the Oil & Gas Sector', 'Driving technological advancement in mature energy companies.', (SELECT id FROM categories WHERE name = 'Engineering & Technical'), '2 Weeks', 'Istanbul', '', 1, 96);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Predictive Analytics for Industrial Failures', 'Utilizing big data to forecast and prevent equipment breakdowns.', (SELECT id FROM categories WHERE name = 'Telecom & Digital'), '1 Week', 'Istanbul', '', 1, 97);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Mega Projects Management in the Oil & Gas Sector', 'Comprehensive methodologies for successfully executing multi-billion dollar capital projects in the global energy industry.', (SELECT id FROM categories WHERE name = 'Engineering & Technical'), '2 Weeks', 'Istanbul', '', 1, 98);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Advanced Analysis of Industrial Incidents', 'In-depth investigative techniques for high-consequence industrial accidents.', (SELECT id FROM categories WHERE name = 'Health, Safety & Environment'), '1 Week', 'Istanbul', '', 1, 99);
INSERT INTO programs (title, description, category_id, duration, location, detail_url, is_published, sort_order) VALUES ('Advanced Automotive EV Diagnostics & Repair', 'Specialized deep-dive into complex electric vehicle fault tracing and component repair.', (SELECT id FROM categories WHERE name = 'Engineering & Technical'), '2 Weeks', 'Istanbul / Global', '', 1, 100);

-- Gallery categories
INSERT INTO gallery_categories (name, slug, badge_class, badge_text, description, sort_order) VALUES ('Firefighter Training', 'firefighter', 'fire', 'Fire Safety & Emergency', 'Live-fire and tactical training delivered at the PETKİM Industrial Fire and Rescue Center, İzmir — a SOCAR subsidiary and one of the most advanced industrial fire facilities in the region.', 0);

-- Gallery images
INSERT INTO gallery_images (gallery_category_id, filename, caption, sort_order) VALUES ((SELECT id FROM gallery_categories WHERE slug = 'firefighter'), 'firefighter-1.jpeg', 'Industrial firefighter training — PETKİM Center, İzmir', 0);
INSERT INTO gallery_images (gallery_category_id, filename, caption, sort_order) VALUES ((SELECT id FROM gallery_categories WHERE slug = 'firefighter'), 'firefighter-2.jpeg', 'Live-fire drill at PETKİM Center, İzmir', 1);
INSERT INTO gallery_images (gallery_category_id, filename, caption, sort_order) VALUES ((SELECT id FROM gallery_categories WHERE slug = 'firefighter'), 'firefighter-3.jpeg', 'Tactical SCBA training', 2);
INSERT INTO gallery_images (gallery_category_id, filename, caption, sort_order) VALUES ((SELECT id FROM gallery_categories WHERE slug = 'firefighter'), 'firefighter-4.jpeg', 'Petrochemical fire response simulation', 3);
INSERT INTO gallery_images (gallery_category_id, filename, caption, sort_order) VALUES ((SELECT id FROM gallery_categories WHERE slug = 'firefighter'), 'firefighter-5.jpeg', 'Hose and nozzle attack team training', 4);
INSERT INTO gallery_images (gallery_category_id, filename, caption, sort_order) VALUES ((SELECT id FROM gallery_categories WHERE slug = 'firefighter'), 'firefighter-6.jpeg', 'JOIFF-accredited firefighter program — graduation drill', 5);

SET FOREIGN_KEY_CHECKS = 1;
